### ISSUE TITLE
Change of action indexes can be breaking for older policies

### ISSUE THREAD

**Issue by dylan-asmar** [JuliaPOMDP/RockSample.jl#34]
The change of the action indexes in https://github.com/JuliaPOMDP/RockSample.jl/commit/a989c320bfb7930969be31005394619c105c6fe8 breaks policies that were generated using older variations. I think this should result in a bump in version number as it isn't compatible with other v0.1.x policies generated before v0.1.6.

**Comment by zsunberg** [comment]
Thanks for reporting! Do you mean you think we should just release v0.2? I would be OK with that.

**Comment by dylan-asmar** [comment]
Yeah, that was basically my idea/thoughts

**Comment by dylan-asmar** [comment]
Fixed with https://github.com/JuliaPOMDP/RockSample.jl/pull/36
